version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data01
        target: /usr/share/elasticsearch/data
      - type: volume
        source: certs
        target: $CERTS_DIR
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      
      network.publish_host: _eth0_
      
      node.name: master-1
      node.roles: master
      
      
      discovery.seed_hosts: es2, es3, es4, es5, es6
      
      cluster.initial_master_nodes: master-1, master-2, master-3
      cluster.name: labangba_cluster

      xpack.security.enabled: 'true'
      xpack.security.http.ssl.key: $CERTS_DIR/elasticsearch/elasticsearch.key
      xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.http.ssl.certificate: $CERTS_DIR/elasticsearch/elasticsearch.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.transport.ssl.certificate: $CERTS_DIR/elasticsearch/elasticsearch.crt
      xpack.security.transport.ssl.key: $CERTS_DIR/elasticsearch/elasticsearch.key
    networks:
      - elk

  es2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data02
        target: /usr/share/elasticsearch/data
      - type: volume
        source: certs
        target: $CERTS_DIR
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      
      network.publish_host: _eth0_
      
      node.name: master-2
      node.roles: master
      
      
      discovery.seed_hosts: elasticsearch, es3, es4, es5, es6
      
      cluster.initial_master_nodes: master-1, master-2, master-3
      cluster.name: labangba_cluster

      xpack.security.enabled: 'true'
      xpack.security.http.ssl.enabled: 'true'
      xpack.security.http.ssl.key: $CERTS_DIR/es2/es2.key
      xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.http.ssl.certificate: $CERTS_DIR/es2/es2.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.transport.ssl.certificate: $CERTS_DIR/es2/es2.crt
      xpack.security.transport.ssl.key: $CERTS_DIR/es2/es2.key
    networks:
      - elk
  
  es3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data03
        target: /usr/share/elasticsearch/data
      - type: volume
        source: certs
        target: $CERTS_DIR
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      
      network.publish_host: _eth0_
      
      node.name: master-3
      node.roles: master
      
      
      discovery.seed_hosts: elasticsearch, es2, es4, es5, es6
      
      cluster.initial_master_nodes: master-1, master-2, master-3
      cluster.name: labangba_cluster

      xpack.security.enabled: 'true'
      xpack.security.http.ssl.key: $CERTS_DIR/es3/es3.key
      xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.http.ssl.certificate: $CERTS_DIR/es3/es3.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.transport.ssl.certificate: $CERTS_DIR/es3/es3.crt
      xpack.security.transport.ssl.key: $CERTS_DIR/es3/es3.key
    networks:
      - elk

  es4:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data04
        target: /usr/share/elasticsearch/data
      - type: volume
        source: certs
        target: $CERTS_DIR
    ports:
      - "9203:9200"
      - "9303:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      
      network.publish_host: _eth0_
      
      node.name: data-1
      node.roles: data
      
      
      discovery.seed_hosts: elasticsearch, es2, es3, es5, es6
      
      cluster.initial_master_nodes: master-1, master-2, master-3
      cluster.name: labangba_cluster
      xpack.security.enabled: 'true'
      xpack.security.http.ssl.key: $CERTS_DIR/es4/es4.key
      xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.http.ssl.certificate: $CERTS_DIR/es4/es4.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.transport.ssl.certificate: $CERTS_DIR/es4/es4.crt
      xpack.security.transport.ssl.key: $CERTS_DIR/es4/es4.key
    networks:
      - elk

  es5:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data05
        target: /usr/share/elasticsearch/data
      - type: volume
        source: certs
        target: $CERTS_DIR
    ports:
      - "9204:9200"
      - "9304:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      
      network.publish_host: _eth0_
      
      node.name: data-2
      node.roles: data
      
      
      discovery.seed_hosts: elasticsearch, es2, es3, es4, es6
      
      cluster.initial_master_nodes: master-1, master-2, master-3
      cluster.name: labangba_cluster

      xpack.security.enabled: 'true'
      xpack.security.http.ssl.key: $CERTS_DIR/es5/es5.key
      xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.http.ssl.certificate: $CERTS_DIR/es5/es5.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.transport.ssl.certificate: $CERTS_DIR/es5/es5.crt
      xpack.security.transport.ssl.key: $CERTS_DIR/es5/es5.key
    networks:
      - elk

  es6:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: data06
        target: /usr/share/elasticsearch/data
      - type: volume
        source: certs
        target: $CERTS_DIR
    ports:
      - "9205:9200"
      - "9305:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      
      network.publish_host: _eth0_
      
      node.name: data-3
      node.roles: data
      
      
      discovery.seed_hosts: elasticsearch, es2, es3, es4, es5
      
      cluster.initial_master_nodes: master-1, master-2, master-3
      cluster.name: labangba_cluster

      xpack.security.enabled: 'true'
      xpack.security.http.ssl.key: $CERTS_DIR/es6/es6.key
      xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.http.ssl.certificate: $CERTS_DIR/es6/es6.crt
      xpack.security.transport.ssl.enabled: 'true'
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
      xpack.security.transport.ssl.certificate: $CERTS_DIR/es6/es6.crt
      xpack.security.transport.ssl.key: $CERTS_DIR/es6/es6.key
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/mysql-connector-java-8.0.25.jar
        target: /usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.25.jar
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - es2
      - es3
      - es4
      - es5
      - es6

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
      - type: volume
        source: certs
        target: $KIBANA_CERTS_DIR
    environment:
      server.ssl.certificate: $KIBANA_CERTS_DIR/kibana/kibana.crt
      server.ssl.key: $KIBANA_CERTS_DIR/kibana/kibana.key
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - es2
      - es3
      - es4
      - es5
      - es6

networks:
  elk:
    driver: bridge

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  data04:
    driver: local
  data05:
    driver: local
  data06:
    driver: local
  certs:
    driver: local